//SECCESS
export const WEATHER_SEARCH_SUCCESS = 'WEATHER_SEARCH_SUCCESS'
export const WEATHER_FIVE_DAYS_SUCCESS = 'WEATHER_FIVE_DAYS_SUCCESS'
export const WEATHER_CURRENT_SUCCESS = 'WEATHER_CURRENT_SUCCESS'
export const ADD_WEATHER_FAVORITE_SUCCESS = 'ADD_WEATHER_FAVORITE_SUCCESS'
export const REMOVE_WEATHER_FAVORITE_SUCCESS = 'REMOVE_WEATHER_FAVORITE_SUCCESS'
//ERROR
export const WEATHER_SEARCH_ERROR = 'WEATHER_SEARCH_ERROR'
export const WEATHER_FIVE_DAYS_ERROR = 'WEATHER_FIVE_DAYS_ERROR'
export const WEATHER_CURRENT_ERROR = 'WEATHER_CURRENT_ERROR'
export const ADD_WEATHER_FAVORITES_ERROR = 'ADD_WEATHER_FAVORITES_ERROR'
export const REMOVE_WEATHER_FAVORITES_ERROR = 'REMOVE_WEATHER_FAVORITES_ERROR'
